Repository pknu-wap/WAPP, pull requests merged in 2023-10, with the labels that each got.

#24 Feature/tgyuu/#22
  app/src/main/java/com/wap/wapp/MainActivity.kt
  app/src/main/res/values/themes.xml
  core/base/src/main/java/com/wap/wapp/core/base/util/repeatOnStarted.kt
  feature/splash/build.gradle.kts
  feature/splash/src/main/java/com/wap/wapp/feature/splash/SplashFragment.kt
  feature/splash/src/main/java/com/wap/wapp/feature/splash/SplashViewModel.kt
  feature/splash/src/main/res/layout/fragment_splash.xml
  feature/splash/src/main/res/navigation/nav_splash.xml
Labels: 🌱기능🌱, 🧩태규🧩, 🌟머지 해주세요🌟

#28 Feature/jaino/#15
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/dictionaries/jaino.xml
  app/src/main/AndroidManifest.xml
  core/data/src/main/java/com/wap/wapp/core/data/di/AuthRepositoryModule.kt
  core/data/src/main/java/com/wap/wapp/core/data/di/DataModule.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/auth/AuthRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/auth/AuthRepositoryImpl.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/user/UserRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/user/UserRepositoryImpl.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/auth/SignInUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/model/AuthState.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/auth/DeleteUserUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/auth/SignInUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/auth/SignOutUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/user/PostUserProfileUseCase.kt
  core/model/src/main/java/com/wap/wapp/core/model/user/UserProfile.kt
  core/network/build.gradle.kts
  core/network/src/main/java/com/wap/wapp/core/network/constant/FirebaseConstant.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/user/UserProfileRequest.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/user/UserProfileResponse.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/auth/AuthDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/auth/AuthDataSourceImpl.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/user/UserDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/user/UserDataSourceImpl.kt
  core/network/src/main/java/com/wap/wapp/core/network/utils/SuspendCoroutine.kt
Labels: 🚀진호🚀, 🌟머지 해주세요🌟

#29 Feature/tgyuu/#26
  app/build.gradle.kts
  app/src/main/java/com/wap/wapp/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/values/arrays.xml
  build-logic/convention/build.gradle.kts
  feature/notice/src/main/res/layout/fragment_notice.xml
  feature/splash/src/main/res/layout/fragment_splash.xml
Labels: 🌱기능🌱, 🧩태규🧩, 🌟머지 해주세요🌟

#34 Feature/jaino/#17
  app/build.gradle.kts
  app/src/main/java/com/wap/wapp/MainActivity.kt
  app/src/main/res/navigation/nav_main.xml
  app/src/main/res/values/arrays.xml
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/java/com/wap/wapp/plugin/AndroidFeatureConventionPlugin.kt
  build-logic/convention/src/main/java/com/wap/wapp/plugin/AndroidNavigationPlugin.kt
  build.gradle.kts
  core/data/src/main/java/com/wap/wapp/core/data/di/AuthRepositoryModule.kt
  core/data/src/main/java/com/wap/wapp/core/data/di/DataModule.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/user/UserRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/user/UserRepositoryImpl.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/auth/SignInUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/user/PostUserProfileUseCase.kt
  core/network/src/main/java/com/wap/wapp/core/network/di/AuthDataSourceModule.kt
  core/network/src/main/java/com/wap/wapp/core/network/di/FirebaseModule.kt
  core/network/src/main/java/com/wap/wapp/core/network/di/NetworkModule.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/user/UserDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/user/UserDataSourceImpl.kt
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signin/SignInBottomSheet.kt
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signin/SignInFragment.kt
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signin/SignInScreen.kt
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signup/SignUpChip.kt
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signup/SignUpFragment.kt
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signup/SignUpScreen.kt
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signup/SignUpTextField.kt
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signup/SignUpViewModel.kt
  feature/auth/src/main/res/navigation/nav_auth.xml
  feature/auth/src/main/res/values/strings.xml
  feature/splash/src/main/java/com/wap/wapp/feature/splash/SplashFragment.kt
  gradle/libs.versions.toml
Labels: 🚀진호🚀, 🌱기능🌱, 🌟머지 해주세요🌟

#37 Feature/jaino/#32
  core/data/src/main/java/com/wap/wapp/core/data/di/DataModule.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/manage/ManageRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/manage/ManageRepositoryImpl.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/model/CodeVerification.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/manage/CheckManagerCodeUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/manage/CheckManagerStatusUseCase.kt
  core/network/src/main/java/com/wap/wapp/core/network/constant/FirebaseConstant.kt
  core/network/src/main/java/com/wap/wapp/core/network/di/NetworkModule.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/manage/ManageDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/manage/ManageDataSourceImpl.kt
Labels: 🚀진호🚀, 🌱기능🌱, 🌟머지 해주세요🌟

#39 Feature/jaino/#38
  app/src/main/java/com/wap/wapp/MainActivity.kt
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/navigation/nav_main.xml
  core/common/src/main/java/com/wap/wapp/core/commmon/extensions/ContextExtensions.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/manage/ManageRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/manage/ManageRepositoryImpl.kt
  core/designsystem/src/main/java/com/wap/designsystem/Color.kt
  core/designsystem/src/main/java/com/wap/designsystem/Type.kt
  core/designsystem/src/main/java/com/wap/designsystem/component/Button.kt
  core/designsystem/src/main/java/com/wap/designsystem/component/TextField.kt
  core/designsystem/src/main/java/com/wap/designsystem/component/TopBar.kt
  core/designsystem/src/main/res/drawable/ic_back.xml
  core/designsystem/src/main/res/drawable/ic_close.xml
  core/designsystem/src/main/res/values/strings.xml
  core/domain/src/main/java/com/wap/wapp/core/domain/model/CodeValidation.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/manage/HasManagerStateUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/manage/ValidateManageCodeUseCase.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/manage/ManageDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/manage/ManageDataSourceImpl.kt
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signin/SignInScreen.kt
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signup/SignUpChip.kt
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signup/SignUpScreen.kt
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signup/SignUpTextField.kt
  feature/manage/build.gradle.kts
  feature/manage/src/main/java/com/wap/wapp/feature/manage/ManageFragment.kt
  feature/manage/src/main/java/com/wap/wapp/feature/manage/ManageScreen.kt
  feature/manage/src/main/java/com/wap/wapp/feature/manage/ManageViewModel.kt
  feature/manage/src/main/java/com/wap/wapp/feature/manage/code/ManageCodeDialog.kt
  feature/manage/src/main/java/com/wap/wapp/feature/manage/code/ManagementCodeViewModel.kt
  feature/manage/src/main/res/layout/fragment_manage.xml
  feature/manage/src/main/res/navigation/nav_management.xml
  feature/manage/src/main/res/values/strings.xml
Labels: 🚀진호🚀, 🌱기능🌱, 🎨유아이🎨, 🌟머지 해주세요🌟

#45 Feature/jaino/#42
  core/data/src/main/java/com/wap/wapp/core/data/di/DataModule.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/survey/SurveyRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/survey/SurveyRepositoryImpl.kt
  core/designresource/src/main/res/drawable/ic_back.xml
  core/designresource/src/main/res/drawable/ic_forward.xml
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/survey/GetSurveyListUseCase.kt
  core/model/src/main/java/com/wap/wapp/core/model/survey/Rating.kt
  core/model/src/main/java/com/wap/wapp/core/model/survey/Survey.kt
  core/network/src/main/java/com/wap/wapp/core/network/constant/FirebaseConstant.kt
  core/network/src/main/java/com/wap/wapp/core/network/di/NetworkModule.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/survey/RatingResponse.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/survey/SurveyResponse.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/survey/SurveyDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/survey/SurveyDataSourceImpl.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementSurveyContent.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementViewModel.kt
  feature/management/src/main/res/values/strings.xml
Labels: 🚀진호🚀, 🌱기능🌱, 🌟머지 해주세요🌟
