Repository pknu-wap/WAPP, pull requests merged in 2023-12, with the labels that each got.

#64 Feature/jaino/#59
  .idea/gradle.xml
  app/src/main/java/com/wap/wapp/navigation/TopLevelDestination.kt
  app/src/main/java/com/wap/wapp/navigation/WappNavHost.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/management/ManagementRepositoryImpl.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/survey/SurveyRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/survey/SurveyRepositoryImpl.kt
  core/designsystem/src/main/java/com/wap/designsystem/component/TextField.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/management/RegisterSurveyUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/survey/GetSurveyFormListUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/survey/GetSurveyFormUseCase.kt
  core/model/src/main/java/com/wap/wapp/core/model/survey/Rating.kt
  core/model/src/main/java/com/wap/wapp/core/model/survey/SurveyForm.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/event/EventRequest.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/event/EventResponse.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/management/SurveyFormRequest.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/survey/SurveyFormResponse.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/survey/SurveyQuestionResponse.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/survey/SurveyDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/survey/SurveyDataSourceImpl.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/check/SurveyCheckScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/registration/survey/SurveyRegistrationScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/registration/survey/SurveyRegistrationViewModel.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/registration/survey/question/SurveyQuestionContent.kt
  feature/survey/build.gradle.kts
  feature/survey/src/main/java/com/wap/wapp/feature/survey/SurveyScreen.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/SurveyViewModel.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/answer/ObjectiveSurveyForm.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/answer/SubjectiveSurveyForm.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/answer/SurveyAnswerScreen.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/answer/SurveyAnswerStateIndicator.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/answer/SurveyAnswerViewModel.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/navigation/SurveyNavigation.kt
  feature/survey/src/main/res/values/strings.xml
Labels: 🌱기능🌱, 🎨유아이🎨, 🌟머지 해주세요🌟

#68 Feature/jaino/#67
  app/src/main/java/com/wap/wapp/navigation/WappNavHost.kt
  core/data/src/main/java/com/wap/wapp/core/data/di/DataModule.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/management/ManagementRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/management/ManagementRepositoryImpl.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/survey/SurveyFormRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/survey/SurveyFormRepositoryImpl.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/survey/SurveyRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/survey/SurveyRepositoryImpl.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/management/RegisterSurveyUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/survey/GetSurveyFormListUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/survey/GetSurveyFormUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/survey/IsSubmittedSurveyUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/survey/PostSurveyUseCase.kt
  core/model/src/main/java/com/wap/wapp/core/model/survey/Survey.kt
  core/network/src/main/java/com/wap/wapp/core/network/di/NetworkModule.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/survey/RatingResponse.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/survey/SurveyRequest.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/survey/SurveyResponse.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/survey/form/SurveyFormRequest.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/survey/form/SurveyFormResponse.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/survey/form/SurveyQuestionResponse.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/management/ManagementDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/management/ManagementDataSourceImpl.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/survey/SurveyDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/survey/SurveyDataSourceImpl.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/survey/SurveyFormDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/survey/SurveyFormDataSourceImpl.kt
  core/network/src/main/java/com/wap/wapp/core/network/utils/LocalDateTime.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementSurveyContent.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/check/SurveyCheckScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/check/navigation/SurveyCheckNavigation.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/navigation/ManagementNavigation.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/SurveyScreen.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/SurveyViewModel.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/answer/SurveyAnswerScreen.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/answer/SurveyAnswerViewModel.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/navigation/SurveyNavigation.kt
  feature/survey/src/main/res/values/strings.xml
Labels: 🚀진호🚀, 🌱기능🌱, 🧹허드렛일🧹, 🌟머지 해주세요🌟

#72 Feature/tgyuu/#70
  core/designresource/src/main/res/drawable/ic_back.xml
  core/designresource/src/main/res/drawable/ic_forward.xml
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/event/GetEventListUseCase.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementViewModel.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/registration/survey/SurveyRegistrationViewModel.kt
  feature/notice/src/main/java/com/wap/wapp/feature/notice/BottomSheetContent.kt
  feature/notice/src/main/java/com/wap/wapp/feature/notice/Calendar.kt
  feature/notice/src/main/java/com/wap/wapp/feature/notice/NoticeScreen.kt
  feature/notice/src/main/java/com/wap/wapp/feature/notice/NoticeViewModel.kt
  feature/notice/src/main/res/values/strings.xml
  feature/profile/src/main/java/com/wap/wapp/feature/profile/ProfileScreen.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/ProfileViewModel.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/component/WappProfileCard.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/profilesetting/ProfileSettingScreen.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/screen/GuestProfile.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/screen/UserProfile.kt
  feature/profile/src/main/res/values/strings.xml
  feature/survey/src/main/java/com/wap/wapp/feature/survey/SurveyScreen.kt
Labels: 🌱기능🌱, 🔧리팩터링🔧, 🧩태규🧩, 🌟머지 해주세요🌟

#71 Feature/tgyuu/#63
  app/build.gradle.kts
  app/src/main/java/com/wap/wapp/MainActivity.kt
  app/src/main/java/com/wap/wapp/component/WappBottomBar.kt
  app/src/main/java/com/wap/wapp/navigation/WappNavHost.kt
  core/designresource/src/main/res/drawable/ic_absent.xml
  core/designresource/src/main/res/drawable/ic_attendance.xml
  core/designresource/src/main/res/drawable/ic_back.xml
  core/designresource/src/main/res/drawable/ic_check.xml
  core/designresource/src/main/res/drawable/ic_forward.xml
  core/designresource/src/main/res/drawable/ic_guest_cat.xml
  core/designresource/src/main/res/drawable/ic_guest_github.xml
  core/designresource/src/main/res/drawable/ic_small_right_arrow.xml
  core/designresource/src/main/res/drawable/ic_yellow_check.xml
  core/designsystem/src/main/java/com/wap/designsystem/Color.kt
  core/designsystem/src/main/java/com/wap/designsystem/component/Card.kt
  core/designsystem/src/main/java/com/wap/designsystem/component/CircleLoader.kt
  core/designsystem/src/main/java/com/wap/designsystem/component/TopBar.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/event/GetEventListUseCase.kt
  core/network/src/main/java/com/wap/wapp/core/network/utils/LocalDateTime.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementEventContent.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementSurveyContent.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementViewModel.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/registration/survey/SurveyRegistrationViewModel.kt
  feature/notice/src/main/java/com/wap/wapp/feature/notice/BottomSheetContent.kt
  feature/notice/src/main/java/com/wap/wapp/feature/notice/Calendar.kt
  feature/notice/src/main/java/com/wap/wapp/feature/notice/NoticeScreen.kt
  feature/notice/src/main/java/com/wap/wapp/feature/notice/NoticeViewModel.kt
  feature/notice/src/main/res/values/strings.xml
  feature/profile/build.gradle.kts
  feature/profile/src/main/java/com/wap/wapp/feature/profile/ProfileScreen.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/ProfileViewModel.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/Role.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/component/WappAttendanceRow.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/component/WappProfileCard.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/component/WappSurveyHistoryRow.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/navigation/ProfileNavigation.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/profilesetting/ProfileSettingScreen.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/profilesetting/navigation/ProfileSettingNavigation.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/screen/GuestProfile.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/screen/UserProfile.kt
  feature/profile/src/main/res/values/strings.xml
  feature/survey/src/main/java/com/wap/wapp/feature/survey/SurveyScreen.kt
Labels: 🌱기능🌱, 🎨유아이🎨, 🔧리팩터링🔧, 🌟머지 해주세요🌟
