Repository pknu-wap/WAPP, pull requests merged in 2023-11, with the labels that each got.

#46 Feature/tgyuu/#25
  app/build.gradle.kts
  app/src/main/res/layout/activity_main.xml
  build-logic/convention/build.gradle.kts
  core/designsystem/src/main/java/com/wap/designsystem/Color.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/model/Notice.kt
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signup/SignUpScreen.kt
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signup/SignUpViewModel.kt
  feature/notice/build.gradle.kts
  feature/notice/src/main/java/com/wap/wapp/feature/notice/NoticeFragment.kt
  feature/notice/src/main/java/com/wap/wapp/feature/notice/NoticeScreen.kt
  feature/notice/src/main/java/com/wap/wapp/feature/notice/NoticeViewModel.kt
  feature/notice/src/main/res/drawable/ic_calendar.png
  feature/notice/src/main/res/drawable/ic_threelines.xml
  feature/notice/src/main/res/values/strings.xml
Labels: 🌱기능🌱, 🧩태규🧩, 🌟머지 해주세요🌟, ✅스타일 ✅

#49 Feature/tgyuu/#47
  .editorconfig
  core/common/src/main/java/com/wap/wapp/core/commmon/util/DateUtil.kt
  core/data/src/main/java/com/wap/wapp/core/data/di/DataModule.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/event/EventRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/event/EventRepositoryImpl.kt
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/wap/designsystem/Color.kt
  core/designsystem/src/main/java/com/wap/designsystem/component/CircleLoader.kt
  core/designsystem/src/main/res/raw/raw_loading.json
  core/domain/src/main/java/com/wap/wapp/core/domain/model/Notice.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/event/GetEventsUseCase.kt
  core/model/src/main/java/com/wap/wapp/core/model/event/Event.kt
  core/network/build.gradle.kts
  core/network/src/main/java/com/wap/wapp/core/network/constant/FirebaseConstant.kt
  core/network/src/main/java/com/wap/wapp/core/network/di/NetworkModule.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/event/EventResponse.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/event/EventDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/event/EventDataSourceImpl.kt
  core/network/src/test/java/com/wap/wapp/core/network/ExampleUnitTest.kt
  feature/notice/build.gradle.kts
  feature/notice/src/main/java/com/wap/wapp/feature/notice/BottomSheetContent.kt
  feature/notice/src/main/java/com/wap/wapp/feature/notice/Calendar.kt
  feature/notice/src/main/java/com/wap/wapp/feature/notice/NoticeFragment.kt
  feature/notice/src/main/java/com/wap/wapp/feature/notice/NoticeScreen.kt
  feature/notice/src/main/java/com/wap/wapp/feature/notice/NoticeViewModel.kt
  feature/notice/src/main/res/drawable/ic_calendar.png
  feature/notice/src/main/res/drawable/ic_cat.xml
  feature/notice/src/main/res/navigation/nav_notice.xml
  feature/notice/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🌱기능🌱, 🎨유아이🎨, 🧩태규🧩, 🌟머지 해주세요🌟

#52 Feature/jaino/#44
  app/src/main/res/values/arrays.xml
  build-logic/convention/build.gradle.kts
  core/designsystem/src/main/java/com/wap/designsystem/component/Title.kt
  core/model/src/main/java/com/wap/wapp/core/model/event/Event.kt
  core/model/src/main/java/com/wap/wapp/core/model/survey/SurveyForm.kt
  core/model/src/main/java/com/wap/wapp/core/model/survey/SurveyQuestion.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/event/EventResponse.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementFragment.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/survey/SurveyRegistrationFragment.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/survey/SurveyRegistrationScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/survey/SurveyRegistrationState.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/survey/SurveyRegistrationViewModel.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/survey/component/SurveyRegistrationTextField.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/survey/deadline/SurveyDeadlineContent.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/survey/event/SurveyEventSelectionContent.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/survey/information/SurveyInformationContent.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/survey/question/SurveyQuestionContent.kt
  feature/management/src/main/res/navigation/nav_management.xml
  feature/management/src/main/res/values/strings.xml
  feature/notice/src/main/java/com/wap/wapp/feature/notice/BottomSheetContent.kt
Labels: 🚀진호🚀, 🎨유아이🎨, 🌟머지 해주세요🌟

#54 Feature/jaino/#53
  core/data/src/main/java/com/wap/wapp/core/data/repository/management/ManagementRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/management/ManagementRepositoryImpl.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/management/RegisterSurveyUseCase.kt
  core/model/src/main/java/com/wap/wapp/core/model/survey/SurveyForm.kt
  core/network/src/main/java/com/wap/wapp/core/network/constant/FirebaseConstant.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/management/SurveyFormRequest.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/management/ManagementDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/management/ManagementDataSourceImpl.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/survey/SurveyRegistrationFragment.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/survey/SurveyRegistrationScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/survey/SurveyRegistrationViewModel.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/survey/question/SurveyQuestionContent.kt
Labels: 🚀진호🚀, 🌱기능🌱, 🧹허드렛일🧹, 🌟머지 해주세요🌟
