Repository pknu-wap/WAPP, pull requests merged in 2024-01, with the labels that each got.

#75 Feature/tgyuu/#74
  app/src/main/java/com/wap/wapp/MainActivity.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/ProfileScreen.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/profilesetting/Const.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/profilesetting/ProfileSettingScreen.kt
Labels: 🌱기능🌱, 🧩태규🧩, 🌟머지 해주세요🌟

#83 Fix/jaino/#81
  .idea/gradle.xml
  app/src/main/java/com/wap/wapp/navigation/WappNavHost.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/management/ManagementRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/management/ManagementRepositoryImpl.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/management/HasManagerStateUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/user/GetUserRoleUseCase.kt
  core/model/src/main/java/com/wap/wapp/core/model/survey/SurveyForm.kt
  core/model/src/main/java/com/wap/wapp/core/model/user/UserRole.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/management/ManagementDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/management/ManagementDataSourceImpl.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/SurveyGuestDialog.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/SurveyScreen.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/SurveyViewModel.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/navigation/SurveyNavigation.kt
  feature/survey/src/main/res/values/strings.xml
Labels: 🚀진호🚀, 🌱기능🌱, 🌟머지 해주세요🌟, 🔨픽스🔨

#91 Feature/tgyuu/#82
  core/designsystem/src/main/java/com/wap/designsystem/component/MainTopBar.kt
  core/designsystem/src/main/java/com/wap/designsystem/component/SubTopBar.kt
  core/designsystem/src/main/res/drawable/ic_subtract.xml
  core/designsystem/src/main/res/values/strings.xml
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signup/SignUpScreen.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/registration/SurveyRegistrationScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/edit/event/EventEditScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/registration/event/EventRegistrationScreen.kt
  feature/management/src/main/res/values/strings.xml
  feature/notice/src/main/java/com/wap/wapp/feature/notice/Calendar.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/ProfileScreen.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/component/WappProfileCard.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/profilesetting/ProfileSettingScreen.kt
  feature/profile/src/main/res/values/strings.xml
  feature/survey-check/src/main/java/com/wap/wapp/feature/survey/check/SurveyCheckScreen.kt
  feature/survey-check/src/main/java/com/wap/wapp/feature/survey/check/SurveyCheckTopBar.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/SurveyScreen.kt
Labels: 🎨유아이🎨, 🔧리팩터링🔧, 🧩태규🧩, 🌟머지 해주세요🌟

#92 Feature/jaino/#90
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementEventCard.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementSurveyCard.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementSurveyContent.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementViewModel.kt
  feature/management/src/main/res/values/strings.xml
Labels: 🚀진호🚀, 🌱기능🌱, 🎨유아이🎨, 🌟머지 해주세요🌟

#96 Feature/jaino/#93
  app/src/main/java/com/wap/wapp/MainActivity.kt
  app/src/main/java/com/wap/wapp/navigation/WappNavHost.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/survey/SurveyFormRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/survey/SurveyFormRepositoryImpl.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/survey/SurveyRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/survey/SurveyRepositoryImpl.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/survey/GetSurveyFormUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/survey/IsSubmittedSurveyUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/survey/PostSurveyFormUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/survey/PostSurveyUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/survey/UpdateSurveyFormUseCase.kt
  core/model/src/main/java/com/wap/wapp/core/model/survey/Survey.kt
  core/model/src/main/java/com/wap/wapp/core/model/survey/SurveyForm.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/survey/SurveyRequest.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/survey/SurveyResponse.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/survey/form/SurveyFormRequest.kt
  core/network/src/main/java/com/wap/wapp/core/network/model/survey/form/SurveyFormResponse.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/survey/SurveyDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/survey/SurveyDataSourceImpl.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/survey/SurveyFormDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/survey/SurveyFormDataSourceImpl.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/SurveyDeadlineContent.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/SurveyEventContent.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/SurveyFormContent.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/SurveyFormState.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/SurveyFormStateIndicator.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/SurveyInformationContent.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/SurveyQuestionContent.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/edit/SurveyFormEditScreen.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/edit/SurveyFormEditViewModel.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/navigation/ManagementSurveyNavigation.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/registration/SurveyEventSelectionContent.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/registration/SurveyFormRegistrationScreen.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/registration/SurveyFormRegistrationViewModel.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/registration/navigation/ManagementSurveyNavigation.kt
  feature/management-survey/src/main/res/values/strings.xml
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementSurveyCard.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/navigation/ManagementNavigation.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/SurveyScreen.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/SurveyViewModel.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/answer/SurveyAnswerScreen.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/answer/SurveyAnswerViewModel.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/navigation/SurveyNavigation.kt
Labels: 🚀진호🚀, 🌱기능🌱, 🧹허드렛일🧹, 🌟머지 해주세요🌟

#98 Feature/jaino/#87
  .idea/gradle.xml
  app/src/main/java/com/wap/wapp/navigation/WappNavHost.kt
  core/data/src/main/java/com/wap/wapp/core/data/di/DataModule.kt
  core/data/src/main/java/com/wap/wapp/core/data/di/SignInRepositoryModule.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/auth/AuthRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/auth/AuthRepositoryImpl.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/auth/SignInRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/auth/SignInRepositoryImpl.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/auth/IsUserSignInUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/auth/SignInUseCase.kt
  core/network/src/main/java/com/wap/wapp/core/network/di/NetworkModule.kt
  core/network/src/main/java/com/wap/wapp/core/network/di/SignInDataSourceModule.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/auth/AuthDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/auth/AuthDataSourceImpl.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/auth/SignInDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/auth/SignInDataSourceImpl.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/edit/SurveyFormEditViewModel.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/registration/SurveyFormRegistrationViewModel.kt
  feature/splash/build.gradle.kts
  feature/splash/src/main/java/com/wap/wapp/feature/splash/SplahScreen.kt
  feature/splash/src/main/java/com/wap/wapp/feature/splash/SplashViewModel.kt
  feature/splash/src/main/java/com/wap/wapp/feature/splash/navigation/SplashNavigation.kt
Labels: 🚀진호🚀, 🌱기능🌱, 🌟머지 해주세요🌟

#103 Feature/jaino/#85
  app/src/main/java/com/wap/wapp/navigation/WappNavHost.kt
  core/designresource/src/main/res/drawable/ic_magnifier.xml
  feature/survey-check/src/main/java/com/wap/wapp/feature/survey/check/SurveyCheckScreen.kt
  feature/survey-check/src/main/java/com/wap/wapp/feature/survey/check/SurveyCheckViewModel.kt
  feature/survey-check/src/main/java/com/wap/wapp/feature/survey/check/SurveyItemCard.kt
  feature/survey-check/src/main/java/com/wap/wapp/feature/survey/check/detail/ObjectiveQuestionCard.kt
  feature/survey-check/src/main/java/com/wap/wapp/feature/survey/check/detail/SubjectiveQuestionCard.kt
  feature/survey-check/src/main/java/com/wap/wapp/feature/survey/check/detail/SurveyDetailScreen.kt
  feature/survey-check/src/main/java/com/wap/wapp/feature/survey/check/detail/SurveyDetailTopBar.kt
  feature/survey-check/src/main/java/com/wap/wapp/feature/survey/check/detail/SurveyDetailViewModel.kt
  feature/survey-check/src/main/java/com/wap/wapp/feature/survey/check/detail/SurveyInformationCard.kt
  feature/survey-check/src/main/java/com/wap/wapp/feature/survey/check/navigation/SurveyCheckNavigation.kt
  feature/survey-check/src/main/res/values/strings.xml
  feature/survey/src/main/java/com/wap/wapp/feature/survey/SurveyContent.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/SurveyFormItemCard.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/SurveyScreen.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/navigation/SurveyNavigation.kt
  feature/survey/src/main/res/values/strings.xml
Labels: 🚀진호🚀, 🌱기능🌱, 🌟머지 해주세요🌟

#100 Feature/tgyuu/#74
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/wap/wapp/navigation/WappNavHost.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/event/EventRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/event/EventRepositoryImpl.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/survey/SurveyRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/survey/SurveyRepositoryImpl.kt
  core/designsystem/src/main/java/com/wap/designsystem/component/MainTopBar.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/event/GetDateEventListUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/event/GetRecentEventListUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/survey/GetUserRespondedSurveyListUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/user/GetUserProfileUseCase.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/event/EventDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/event/EventDataSourceImpl.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/survey/SurveyDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/survey/SurveyDataSourceImpl.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/edit/SurveyFormEditViewModel.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/registration/SurveyFormRegistrationViewModel.kt
  feature/notice/src/main/java/com/wap/wapp/feature/notice/BottomSheetContent.kt
  feature/notice/src/main/java/com/wap/wapp/feature/notice/NoticeViewModel.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/ProfileScreen.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/ProfileViewModel.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/Role.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/component/WappAttendanceRow.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/component/WappSurveyHistoryRow.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/navigation/ProfileNavigation.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/profilesetting/ProfileSettingScreen.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/profilesetting/ProfileSettingViewModel.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/profilesetting/component/GuestProfile.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/profilesetting/component/NoContentColumn.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/profilesetting/component/ProfileSettingDialog.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/profilesetting/component/UserProfile.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/profilesetting/navigation/ProfileSettingNavigation.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/screen/UserProfile.kt
  feature/profile/src/main/res/values/strings.xml
Labels: 🌱기능🌱, 🎨유아이🎨, 🔧리팩터링🔧, 🧩태규🧩, 🌟머지 해주세요🌟

#108 Fix/jaino/#107
  app/src/main/java/com/wap/wapp/navigation/WappNavHost.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/management/HasManagerStateUseCase.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementEventCard.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementGuestScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementSurveyCard.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementViewModel.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/navigation/ManagementNavigation.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/validation/ManagementCodeValidationDialog.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/validation/ManagementValidationScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/validation/ManagementValidationViewModel.kt
  feature/management/src/main/res/values/strings.xml
  feature/survey/src/main/java/com/wap/wapp/feature/survey/SurveyGuestDialog.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/SurveyGuestScreen.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/SurveyScreen.kt
Labels: 🚀진호🚀, 🌟머지 해주세요🌟, 🔨픽스🔨

#109 Feature/tgyuu/#105
  .idea/misc.xml
  app/src/main/java/com/wap/wapp/MainActivity.kt
  app/src/main/java/com/wap/wapp/navigation/WappNavHost.kt
  app/src/main/res/values/colors.xml
  core/data/src/main/java/com/wap/wapp/core/data/repository/event/EventRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/event/EventRepositoryImpl.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/survey/SurveyFormRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/survey/SurveyFormRepositoryImpl.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/survey/SurveyRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/survey/SurveyRepositoryImpl.kt
  core/designsystem/src/main/java/com/wap/designsystem/component/SubTopBar.kt
  core/designsystem/src/main/res/values/strings.xml
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/event/DeleteEventAndRelatedSurveysUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/survey/DeleteSurveyFormAndRelatedSurveysUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/survey/DeleteSurveyUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/survey/GetSurveyFormListUseCase.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/auth/AuthDataSourceImpl.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/auth/SignInDataSourceImpl.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/event/EventDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/event/EventDataSourceImpl.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/survey/SurveyDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/survey/SurveyDataSourceImpl.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/survey/SurveyFormDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/survey/SurveyFormDataSourceImpl.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/user/UserDataSourceImpl.kt
  feature/management-event/src/main/java/com/wap/wapp/feature/management/event/edit/EventEditScreen.kt
  feature/management-event/src/main/java/com/wap/wapp/feature/management/event/edit/EventEditViewModel.kt
  feature/management-event/src/main/java/com/wap/wapp/feature/management/event/navigation/ManagementEventNavigation.kt
  feature/management-event/src/main/res/values/strings.xml
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/edit/SurveyFormEditScreen.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/edit/SurveyFormEditViewModel.kt
  feature/management-survey/src/main/res/values/strings.xml
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementEventCard.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementViewModel.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/navigation/ManagementNavigation.kt
Labels: 🌱기능🌱, 🔧리팩터링🔧, 🧩태규🧩, 🌟머지 해주세요🌟

#118 Feature/tgyuu/#115
  .idea/misc.xml
  core/network/src/main/java/com/wap/wapp/core/network/source/attendancestatus/AttendanceStatusDataSourceImpl.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/event/EventDataSourceImpl.kt
  core/network/src/main/java/com/wap/wapp/core/network/utils/DateUtil.kt
  core/network/src/main/java/com/wap/wapp/core/network/utils/LocalDateTime.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/profilesetting/Const.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/profilesetting/ProfileSettingScreen.kt
Labels: 🧹허드렛일🧹, 🧩태규🧩, 🔥리뷰 기다리는 중🔥, 🌟머지 해주세요🌟
