Repository pknu-wap/WAPP, pull requests merged in 2024-02, with the labels that each got.

#111 Feature/jaino/#94
  .idea/gradle.xml
  app/src/main/java/com/wap/wapp/MainActivity.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementSurveyCard.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementViewModel.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/SurveyFormItemCard.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/answer/ObjectiveSurveyForm.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/answer/SubjectiveSurveyForm.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/answer/SurveyAnswerForm.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/answer/SurveyAnswerScreen.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/answer/SurveyAnswerState.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/answer/SurveyAnswerViewModel.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/answer/SurveyOverview.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/navigation/SurveyNavigation.kt
  feature/survey/src/main/res/values/strings.xml
Labels: 🚀진호🚀, 🌱기능🌱, 🎨유아이🎨, 🌟머지 해주세요🌟

#120 Fix/tgyuu/#112
  app/src/main/java/com/wap/wapp/MainActivity.kt
  core/designsystem/src/main/java/com/wap/designsystem/component/SubTopBar.kt
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signup/SignUpScreen.kt
  feature/management-event/src/main/java/com/wap/wapp/feature/management/event/edit/EventEditScreen.kt
  feature/management-event/src/main/java/com/wap/wapp/feature/management/event/registration/EventRegistrationContent.kt
  feature/management-event/src/main/java/com/wap/wapp/feature/management/event/registration/EventRegistrationScreen.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/SurveyFormStateIndicator.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/edit/SurveyFormEditScreen.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/registration/SurveyFormRegistrationScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/ManagementSurveyCard.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/profilesetting/ProfileSettingScreen.kt
Labels: 🎨유아이🎨, 🧩태규🧩, 🌟머지 해주세요🌟, 🔨픽스🔨

#121 Feature/jaino/#95
  app/src/main/java/com/wap/wapp/MainActivity.kt
  core/designresource/src/main/res/drawable/ic_add_question.xml
  core/designresource/src/main/res/drawable/ic_back.xml
  core/designresource/src/main/res/drawable/ic_close.xml
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/EventsState.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/SurveyDeadlineContent.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/SurveyEventContent.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/SurveyFormContent.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/SurveyInformationContent.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/SurveyQuestionContent.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/edit/SurveyDeleteDialog.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/edit/SurveyFormEditScreen.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/edit/SurveyFormEditViewModel.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/registration/SurveyFormRegistrationScreen.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/registration/SurveyFormRegistrationViewModel.kt
  feature/management-survey/src/main/res/values/strings.xml
Labels: 🚀진호🚀, 🌱기능🌱, 🌟머지 해주세요🌟

#123 Feature/tgyuu/#116
  app/src/main/java/com/wap/wapp/MainActivity.kt
  app/src/main/java/com/wap/wapp/navigation/WappNavHost.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/attendance/AttendanceDataSourceImpl.kt
  feature/attendance/src/main/java/com/wap/wapp/feature/attendance/AttendanceScreen.kt
  feature/attendance/src/main/java/com/wap/wapp/feature/attendance/AttendanceViewModel.kt
Labels: 🧹허드렛일🧹, 🧩태규🧩, 🌟머지 해주세요🌟, 🔨픽스🔨

#131 Feature/tgyuu/#129
  core/designresource/src/main/res/drawable/ic_return.xml
  feature/notice/src/main/java/com/wap/wapp/feature/notice/BottomSheetContent.kt
  feature/notice/src/main/java/com/wap/wapp/feature/notice/Calendar.kt
  feature/notice/src/main/res/values/strings.xml
Labels: 🌱기능🌱, 🎨유아이🎨, 🧩태규🧩, 🌟머지 해주세요🌟

#138 Refactor/tgyuu/#134
  feature/attendance/src/main/java/com/wap/wapp/feature/attendance/AttendanceScreen.kt
  feature/attendance/src/main/java/com/wap/wapp/feature/attendance/AttendanceViewModel.kt
  feature/attendance/src/main/java/com/wap/wapp/feature/attendance/component/AttendanceDialog.kt
  feature/attendance/src/main/java/com/wap/wapp/feature/attendance/component/AttendanceItemCard.kt
  feature/attendance/src/main/java/com/wap/wapp/feature/attendance/management/component/AttendanceItemCard.kt
  feature/attendance/src/main/java/com/wap/wapp/feature/attendance/management/component/AttendanceManagementDialog.kt
  feature/profile/src/main/java/com/wap/wapp/feature/profile/profilesetting/ProfileSettingScreen.kt
  feature/survey/src/main/java/com/wap/wapp/feature/survey/answer/SurveyOverview.kt
Labels: 🎨유아이🎨, 🔧리팩터링🔧, 🧩태규🧩, 🌟머지 해주세요🌟

#143 Feature/jaino/#126
  .idea/gradle.xml
  feature/management-event/src/main/java/com/wap/wapp/feature/management/event/edit/EventEditScreen.kt
  feature/management-event/src/main/java/com/wap/wapp/feature/management/event/edit/EventEditViewModel.kt
  feature/management-event/src/main/java/com/wap/wapp/feature/management/event/registration/EventRegistrationContent.kt
  feature/management-event/src/main/java/com/wap/wapp/feature/management/event/registration/EventRegistrationScreen.kt
  feature/management-event/src/main/java/com/wap/wapp/feature/management/event/registration/EventRegistrationViewModel.kt
  feature/management-event/src/main/res/values/strings.xml
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/SurveyDeadlineContent.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/SurveyEventContent.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/SurveyFormContent.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/SurveyInformationContent.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/SurveyQuestionContent.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/edit/SurveyFormEditScreen.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/registration/SurveyFormRegistrationScreen.kt
  feature/management-survey/src/main/res/values/strings.xml
  feature/survey/src/main/java/com/wap/wapp/feature/survey/answer/SurveyAnswerForm.kt
  feature/survey/src/main/res/values/strings.xml
Labels: 🚀진호🚀, 🌱기능🌱, 🎨유아이🎨, 🌟머지 해주세요🌟
