Repository pknu-wap/WAPP, pull requests merged in 2024-03, with the labels that each got.

#145 Feature/tgyuu/#141
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/wap/wapp/navigation/WappNavHost.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/auth/AuthRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/auth/AuthRepositoryImpl.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/management/ManagementRepository.kt
  core/data/src/main/java/com/wap/wapp/core/data/repository/management/ManagementRepositoryImpl.kt
  core/designsystem/src/main/java/com/wap/designsystem/component/Button.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/auth/CheckMemberCodeUseCase.kt
  core/domain/src/main/java/com/wap/wapp/core/domain/usecase/management/CheckManagementCodeUseCase.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/auth/AuthDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/auth/AuthDataSourceImpl.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/management/ManagementDataSource.kt
  core/network/src/main/java/com/wap/wapp/core/network/source/management/ManagementDataSourceImpl.kt
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signin/SignInContent.kt
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signin/SignInScreen.kt
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signup/SignUpScreen.kt
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signup/SignUpViewModel.kt
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signup/navigation/SignUpNavigation.kt
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signup/validation/CodeValidationDialog.kt
  feature/auth/src/main/res/values/strings.xml
  feature/management/src/main/java/com/wap/wapp/feature/management/validation/ManagementValidationScreen.kt
  feature/management/src/main/java/com/wap/wapp/feature/management/validation/ManagementValidationViewModel.kt
Labels: 🌱기능🌱, 🧩태규🧩, 🌟머지 해주세요🌟

#152 Feature/jaino/#117
  feature/auth/src/main/java/com/wap/wapp/feature/auth/signin/SignInScreen.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/SurveyFormContent.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/SurveyQuestionContent.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/edit/SurveyFormEditScreen.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/edit/SurveyFormEditViewModel.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/registration/SurveyFormRegistrationScreen.kt
  feature/management-survey/src/main/java/com/wap/wapp/feature/management/survey/registration/SurveyFormRegistrationViewModel.kt
  feature/management-survey/src/main/res/values/strings.xml
Labels: 🚀진호🚀, 🌱기능🌱, 🎨유아이🎨, 🌟머지 해주세요🌟

#156 [RELEASE] WAPP 1.0.0v
  release-note.txt
Labels: 🚀진호🚀, 🧩태규🧩

#157 Release 1.0.0v
  .github/workflows/released-app-distribution.yml
  build-logic/convention/src/main/java/com/wap/wapp/plugin/AndroidApplicationPlugin.kt
  build-logic/convention/src/main/java/com/wap/wapp/plugin/configure/AndroidVersion.kt
  gradle.properties
  gradle/libs.versions.toml
  release-note.txt
Labels: 🚀진호🚀

#162 Feature/tgyuu/#161
  .github/workflows/closed-pr-notification.yml
  .github/workflows/opened-pr-notification.yml
  .github/workflows/released-app-distribution.yml
  .idea/deploymentTargetDropDown.xml
  README.md
  app/src/main/java/com/wap/wapp/navigation/WappNavHost.kt
  feature/splash/src/main/java/com/wap/wapp/feature/splash/SplahScreen.kt
  feature/splash/src/main/java/com/wap/wapp/feature/splash/SplashViewModel.kt
  feature/splash/src/main/res/drawable/ic_splash_logo.png
  gradle.properties
Labels: 🧩태규🧩, 🌟머지 해주세요🌟, 🔥핫픽스🔥
